### ISSUE TITLE
parsing fails as rmail tries to modify a frozen string

### ISSUE THREAD

**Issue by coffeeaddict** [matta/rubymail#1]
The exact output is this:

```
/opt/ruby-1.9.1-p0/lib/ruby/gems/1.9.1/gems/rmail-1.0.0/lib/rmail/parser/multipart.rb:159:in `[]=': can't modify frozen string (RuntimeError)
    from /opt/ruby-1.9.1-p0/lib/ruby/gems/1.9.1/gems/rmail-1.0.0/lib/rmail/parser/multipart.rb:159:in `block in read_chunk_low'
    from /opt/ruby-1.9.1-p0/lib/ruby/gems/1.9.1/gems/rmail-1.0.0/lib/rmail/parser/multipart.rb:94:in `loop'
    from /opt/ruby-1.9.1-p0/lib/ruby/gems/1.9.1/gems/rmail-1.0.0/lib/rmail/parser/multipart.rb:94:in `read_chunk_low'
    from /opt/ruby-1.9.1-p0/lib/ruby/gems/1.9.1/gems/rmail-1.0.0/lib/rmail/parser/multipart.rb:76:in `read_chunk'
    from /opt/ruby-1.9.1-p0/lib/ruby/gems/1.9.1/gems/rmail-1.0.0/lib/rmail/parser/pushbackreader.rb:85:in `read'
    from /opt/ruby-1.9.1-p0/lib/ruby/gems/1.9.1/gems/rmail-1.0.0/lib/rmail/parser.rb:285:in `parse_singlepart_body'
    from /opt/ruby-1.9.1-p0/lib/ruby/gems/1.9.1/gems/rmail-1.0.0/lib/rmail/parser.rb:198:in `parse_low'
    from /opt/ruby-1.9.1-p0/lib/ruby/gems/1.9.1/gems/rmail-1.0.0/lib/rmail/parser.rb:275:in `parse_multipart_body'
    from /opt/ruby-1.9.1-p0/lib/ruby/gems/1.9.1/gems/rmail-1.0.0/lib/rmail/parser.rb:196:in `parse_low'
    from /opt/ruby-1.9.1-p0/lib/ruby/gems/1.9.1/gems/rmail-1.0.0/lib/rmail/parser.rb:183:in `parse'
    from /opt/ruby-1.9.1-p0/lib/ruby/gems/1.9.1/gems/rmail-1.0.0/lib/rmail/parser.rb:331:in `parse'
    from /opt/ruby-1.9.1-p0/lib/ruby/gems/1.9.1/gems/rmail-1.0.0/lib/rmail/parser.rb:345:in `read'
    from ./bin/mbox-unique.rb:16:in `block in <main>'
    from /opt/ruby-1.9.1-p0/lib/ruby/gems/1.9.1/gems/rmail-1.0.0/lib/rmail/mailbox/mboxreader.rb:130:in `each_message'
    from ./bin/mbox-unique.rb:15:in `<main>'
```

I cant yet tell how and when the issue occurs, but a simple escape plan might just fix it. I will send the pull request shortly.

Grtz,
Hartog.

[edit] The same things happens on a ruby1.8 interpreter so its not a 1.9 issue [/edit]

**Comment by matta** [comment]
My apologies for not responding!  If it isn't painfully obvious, I am no longer maintaining RubyMail.

The maintenance of this package is now done at https://github.com/terceiro/rmail.  Please feel free to resend the bug there.
